version: '3.5'

networks:
  default:
    name: bailfacile

services:
  mysql:
    cap_add:
      - SYS_NICE # https://github.com/docker-library/mysql/issues/303#issuecomment-822684258
    command: --sql-mode=NO_ENGINE_SUBSTITUTION
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bailfacile
    image: mysql:8.0.24
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql

  php:
    container_name: php
    build:
      context: ./php
    ports:
      - '9000:9000'
    volumes:
      - ./app:/var/www/app
    depends_on:
      - mysql

  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    ports:
      - '8080:80'
    volumes:
      - ./app:/var/www/app
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql

volumes:
  mysql_data:
    name: mysql_data
